USE [master]
GO
ALTER DATABASE [QPAccountsDB] SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE [QPAccountsDB] SET RECOVERY SIMPLE --简单模式
GO
USE [QPAccountsDB]
GO
DBCC SHRINKFILE (N'QPAccountsDB_log' , 11, TRUNCATEONLY)
GO

ALTER DATABASE [QPAgencyDB] SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE [QPAgencyDB] SET RECOVERY SIMPLE --简单模式
GO
USE [QPAgencyDB]
GO
DBCC SHRINKFILE (N'QPAgencyDB_log' , 11, TRUNCATEONLY)
GO

ALTER DATABASE [QPEducateDB] SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE [QPEducateDB] SET RECOVERY SIMPLE --简单模式
GO
USE [QPEducateDB]
GO
DBCC SHRINKFILE (N'QPEducateDB_log' , 11, TRUNCATEONLY)
GO

ALTER DATABASE [QPGameMatchDB] SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE [QPGameMatchDB] SET RECOVERY SIMPLE --简单模式
GO
USE [QPGameMatchDB]
GO
DBCC SHRINKFILE (N'QPGameMatchDB_log' , 11, TRUNCATEONLY)
GO

ALTER DATABASE [QPGameWeb] SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE [QPGameWeb] SET RECOVERY SIMPLE --简单模式
GO
USE [QPGameWeb]
GO
DBCC SHRINKFILE (N'QPGameWeb_log' , 11, TRUNCATEONLY)
GO

ALTER DATABASE [QPLogDB] SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE [QPLogDB] SET RECOVERY SIMPLE --简单模式
GO
USE [QPLogDB]
GO
DBCC SHRINKFILE (N'QPLogDB_log' , 11, TRUNCATEONLY)
GO

ALTER DATABASE [QPPlatformDB] SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE [QPPlatformDB] SET RECOVERY SIMPLE --简单模式
GO
USE [QPPlatformDB]
GO
DBCC SHRINKFILE (N'QPPlatformDB_log' , 11, TRUNCATEONLY)
GO

ALTER DATABASE [QPOtherWebDB] SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE [QPOtherWebDB] SET RECOVERY SIMPLE --简单模式
GO
USE [QPOtherWebDB]
GO
DBCC SHRINKFILE (N'QPOtherWebDB_log' , 11, TRUNCATEONLY)
GO

ALTER DATABASE [QPRecordDB] SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE [QPRecordDB] SET RECOVERY SIMPLE --简单模式
GO
USE [QPRecordDB]
GO
DBCC SHRINKFILE (N'QPRecordDB_log' , 11, TRUNCATEONLY)
GO

ALTER DATABASE [QPTreasureDB] SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE [QPTreasureDB] SET RECOVERY SIMPLE --简单模式
GO
USE [QPTreasureDB]
GO
DBCC SHRINKFILE (N'QPTreasureDB_log' , 11, TRUNCATEONLY)
GO
