USE [master]
GO
/****** 对象:  Database [QPAgencyDB]    脚本日期: 07/29/2014 16:11:52 ******/
CREATE DATABASE [QPAgencyDB]
COLLATE Chinese_PRC_CI_AS
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'QPAgencyDB', @new_cmptlevel=90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QPAgencyDB].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [QPAgencyDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QPAgencyDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QPAgencyDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QPAgencyDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QPAgencyDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [QPAgencyDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [QPAgencyDB] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [QPAgencyDB] SET AUTO_SHRINK ON 
GO
ALTER DATABASE [QPAgencyDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QPAgencyDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QPAgencyDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QPAgencyDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QPAgencyDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QPAgencyDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QPAgencyDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QPAgencyDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [QPAgencyDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QPAgencyDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QPAgencyDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QPAgencyDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QPAgencyDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QPAgencyDB] SET  READ_WRITE 
GO
ALTER DATABASE [QPAgencyDB] SET RECOVERY FULL 
GO
ALTER DATABASE [QPAgencyDB] SET  MULTI_USER 
GO
ALTER DATABASE [QPAgencyDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QPAgencyDB] SET DB_CHAINING OFF 