
[config]
StorageStart = 100	;起始库存
StorageDeduct=10	;千分比
Multiple = 1		;下注倍数
UserLimitScore=20000	;个人下注限制(包括机器人)
AllRobotTotalLimitScore=100000	;所有机器人下注总数限制

//时间控制  每次重置，都是在下分时间
FreeTime = 10		; 空闲时间(至少10秒)说明：若设置的时间少于１０秒，默认按至少时间来设定空闲时间
BetTime = 20		; 下注时间(至少10秒)说明：若设置的时间少于１０秒，默认按至少时间来设定下注时间
EndTime = 15		; 结束时间(至少20秒)说明：若设置的时间少于２０秒，默认按至少时间来设定结束时间


; 可以配置10个奖励选项
RewardsProb1=20		; 奖励概率
RewardsLev1=10000	; 分数等级，当库存小于该值时，按照上面的概率奖励出去
RewardsProb2=50		; 奖励概率
RewardsLev2=100000	; 分数等级，当库存小于该值时，按照上面的概率奖励出去


//机器人存款取款
RobotScoreMin=100000				; 机器人的分数小于该值时执行取款
RobotScoreMax=10000000				; 机器人的分数大于该值时执行存款
RobotBankGet=1000000				; 取款最小数额(取款数是该值以上的一个随机数)
RobotBankGetBanker=10000000			; 取款最大数额(此数值一定要大于RobotBankGet)
RobotBankStoMul=10				; 存款百分比，百分之N


;机器人控制
RobotBetCount=550				;机器下注总次数
RobotMaxBet=100					;机器人筹码范围(上限)
RobotMinBet=1					;机器人筹码范围(下限)(当庄家金币太少或机器人自己金币太少或下注次数太大或下注机器人太多时会导致单次下注额度不足下限，机器人下注筹码会低于这范围)
RobotMaxBetTime=50				;机器人下注次数范围(上限)(默认4次)  最大50次
RobotMinBetTime=30				;机器人下注次数范围(下限)(默认8次)


UserBlackLimitScore=10000			;黑桃限制
UserRedLimitScore  =10000			;红桃限制
UserFlowerLimitScore=10000			;梅花限制
UserSquareLimitScore=10000			;方块限制
UserKingLimitScore =1000;			;大小王限制


AreaChance1=26					;黑桃下注概率(默认10)
AreaChance2=25					;红桃下注概率(默认10)
AreaChance3=24					;梅花下注概率(默认10)
AreaChance4=24					;方块下注概率(默认10)
AreaChance5=1					;大小王下注概率(默认10)
[public]
StorageDeduct=5
