////////////////////////////////////////////////////////////////////////////////
[public]
// 初始库存 
StorageStart=800
// 库存衰减值 
StorageDeduct=0

// 是否开启库存控制 1-开启 0- 不开启
IsStockCantrol=1

//单张牌的概率
OxProb0=45
//对子牌的概率
OxProb1=35
//顺子牌的概率
OxProb2=20
//金花牌的概率
OxProb3=5
//顺金牌的概率
OxProb4=4
//豹子牌的概率
OxProb5=1
//控制牌型发牌概率
OxProb6=50

MinLostScore=25		;输分限制下限值,每局机器人输分最小限制 没有到达这个值之前,机器人压注的机率会很大,超过了这个值,就会比牌或者放弃,受库存应响
MaxLostScore=30		;输分限制上限值,每局机器人输分最大限制 没有到达这个值之前,机器人压注的机率会很大,超过了这个值,就会比牌或者放弃,受库存应响

;(机器人下注大于MinLostScore随机看牌,小于取最小看牌概率,大于MaxLostScore,取最大看牌概率)
MinLostIndex=50			;看牌最小机率
MaxLostIndex=100		;看牌最大机率

RobotFirstAddScore=60		;机器人第一圈加注或跟注的机率
RobotShunZiAddScore=60		;机器人在不是第一圈牌型为顺子的加注机率
RobotBigAddScore=60		;机器人在不是第一圈牌型为金花，顺金，豹子的加注机率

//机器人存款取款
RobotScoreMin=25		; 机器人的分数小于该值时执行取款
RobotScoreMax=100		; 机器人的分数大于该值时执行存款
RobotBankGet=10			; 取款最小数额(取款数是该值以上的一个随机数)
RobotBankGetBanker=50	; 取款最大数额(此数值一定要大于RobotBankGet)
RobotBankStoMul=50		; 存款百分比，百分之N


[IdControl]
