USE [master]
GO
/****** :  Database [QPNativeWebDB]    ű: 04/15/2011 16:38:08 ******/
-- 创建数据库 QPNativeWebDB
IF NOT EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N'QPNativeWebDB')
CREATE DATABASE [QPNativeWebDB] COLLATE Chinese_PRC_CI_AS
GO
GO
ALTER DATABASE [QPNativeWebDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QPNativeWebDB].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [QPNativeWebDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QPNativeWebDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QPNativeWebDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QPNativeWebDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QPNativeWebDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [QPNativeWebDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [QPNativeWebDB] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [QPNativeWebDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QPNativeWebDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QPNativeWebDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QPNativeWebDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QPNativeWebDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QPNativeWebDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QPNativeWebDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QPNativeWebDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QPNativeWebDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [QPNativeWebDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QPNativeWebDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QPNativeWebDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QPNativeWebDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QPNativeWebDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QPNativeWebDB] SET  READ_WRITE 
GO
ALTER DATABASE [QPNativeWebDB] SET RECOVERY FULL 
GO
ALTER DATABASE [QPNativeWebDB] SET  MULTI_USER 
GO
ALTER DATABASE [QPNativeWebDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QPNativeWebDB] SET DB_CHAINING OFF 