USE QPPlatformDB
GO

-- ’æµ„≈‰÷√
TRUNCATE TABLE GrowLevelConfig
GO
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (2, 100, 1000, 0, N'2º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (3, 200, 1000, 0, N'3º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (4, 300, 1000, 0, N'4º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (5, 400, 1000, 0, N'5º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (6, 500, 1000, 0, N'6º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (7, 600, 1000, 0, N'7º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (8, 800, 1000, 0, N'8º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (9, 900, 1000, 0, N'9º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (10, 1000, 1000, 0, N'10º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (11, 2000, 1000, 5, N'11º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (12, 3000, 1000, 5, N'12º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (13, 4000, 1000, 5, N'13º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (14, 5000, 1000, 5, N'14º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (15, 6000, 1000, 5, N'15º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (16, 7000, 1000, 5, N'16º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (17, 8000, 1000, 5, N'17º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (18, 9000, 1000, 5, N'18º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (19, 11000, 1000, 5, N'19º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (20, 12000, 1000, 5, N'20º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (21, 13000, 2000, 10, N'21º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (22, 14000, 2000, 10, N'22º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (23, 15000, 2000, 10, N'23º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (24, 16000, 2000, 10, N'24º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (25, 17000, 2000, 10, N'25º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (26, 18000, 2000, 10, N'26º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (27, 19000, 2000, 10, N'27º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (28, 20000, 2000, 10, N'28º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (29, 21000, 2000, 10, N'29º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (30, 22000, 2000, 10, N'30º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (31, 23000, 3000, 15, N'31º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (32, 24000, 3000, 15, N'32º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (33, 25000, 3000, 15, N'33º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (34, 26000, 3000, 15, N'34º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (35, 27000, 3000, 15, N'35º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (36, 28000, 3000, 15, N'36º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (37, 29000, 3000, 15, N'37º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (38, 30000, 3000, 15, N'38º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (39, 31000, 3000, 15, N'39º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (40, 32000, 3000, 15, N'40º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (41, 33000, 4000, 20, N'41º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (42, 34000, 4000, 20, N'42º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (43, 35000, 4000, 20, N'43º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (44, 36000, 4000, 20, N'44º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (45, 37000, 4000, 20, N'45º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (46, 38000, 4000, 20, N'46º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (47, 39000, 4000, 20, N'47º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (48, 40000, 4000, 20, N'48º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (49, 41000, 4000, 20, N'49º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (50, 42000, 4000, 20, N'50º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (51, 43000, 5000, 30, N'51º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (52, 44000, 5000, 30, N'52º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (53, 45000, 5000, 30, N'53º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (54, 46000, 5000, 30, N'54º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (55, 47000, 5000, 30, N'55º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (56, 48000, 5000, 30, N'56º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (57, 400000, 5000, 30, N'57º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (58, 500000, 5000, 30, N'58º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (59, 800000, 5000, 30, N'59º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (60, 1000000, 10000, 30, N'60º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (61, 2000000, 10000, 30, N'61º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (62, 3000000, 10000, 30, N'62º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (63, 4000000, 10000, 30, N'63º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (64, 5000000, 10000, 30, N'64º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (65, 6000000, 10000, 30, N'65º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (66, 7000000, 10000, 30, N'66º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (67, 8000000, 10000, 30, N'67º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (68, 9000000, 10000, 30, N'68º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (69, 10000000, 10000, 30, N'69º∂≈‰÷√')
INSERT INTO [dbo].[GrowLevelConfig] ([LevelID], [Experience], [RewardGold], [RewardMedal], [LevelRemark]) VALUES (70, 20000000, 10000, 30, N'70º∂≈‰÷√')
GO