use QPAccountsDB

-- 系统设置
TRUNCATE TABLE [dbo].[SystemStatusInfo]

INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'BankPrerequisite', 0, N'存取条件，存取金豆必须大于此数才可操作！', N'存取条件', N'键值：表示存取金豆数必须大于此数才可存取', 35)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'EnjoinInsure', 0, N'由于系统维护，暂时停止游戏系统的保险柜服务，请留意网站公告信息！', N'银行服务', N'键值：0-开启，1-关闭', 30)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'EnjoinLogon', 0, N'由于系统维护，暂时停止游戏系统的登录服务，请留意网站公告信息！', N'登录服务', N'键值：0-开启，1-关闭', 25)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'EnjoinRegister', 0, N'由于系统维护，暂时停止游戏系统的注册服务，请留意网站公告信息！', N'注册服务', N'键值：0-开启，1-关闭', 10)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'IPCount', 3, N'一个IP每天注册帐号个数限制！', N'注册帐号限制', N'键值：表示同一个IP最多注册帐号的个数，超过此数将不能注册帐号', 20)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'GrantIPCount', 5, N'新用户注册每天赠送限制！', N'注册赠送限制', N'键值：表示同一个IP最多赠送的次数，超过此数将不赠送金豆', 20)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'GrantScoreCount', 20000, N'新用户注册系统送金豆的数目！', N'注册赠送', N'键值：表示赠送的金豆数量', 15)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'MedalExchangeRate', 1000, N'元宝与金豆兑换率', N'元宝兑换率', N'键值：1个元宝兑换多少金豆', 90)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'PresentExchangeRate', 1500, N'魅力与金豆兑换率', N'魅力兑换率', N'键值: 1点魅力兑换多少金豆', 95)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'RateCurrency', 20000, N'人民币与金豆的汇率 人民币:金豆', N'网银充值汇率', N'键值：人民币与金豆的汇率', 1)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'RateGold', 1, N'游戏豆与金豆的汇率 游戏豆:金豆', N'金豆汇率', N'键值：游戏豆与金豆的汇率', 5)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'RevenueRateTake', 0, N'取款操作税收比率（千分比）！', N'取款税率', N'键值：表示银行取款操作税收比率值（千分比）！', 40)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'RevenueRateTransfer', 10, N'转账操作税收比率（千分比）！', N'普通转账税率', N'键值：表示普通玩家银行转账操作税收比率值（千分比）！', 55)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'RevenueRateTransferMember', 0, N'转账操作会员税收比率（千分比）！', N'会员转账税率', N'键值：表示会员玩家银行转账操作税收比率值（千分比）！', 60)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'SubsistenceAllowancesCondition', 1000, N'领取低保玩家金豆不能低于', N'低保领取条件', N'键值：领取低保玩家金豆不能低于该金豆数', 80)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'SubsistenceAllowancesGold', 1000, N'每次低保的金豆数', N'低保每次金额', N'键值：每次低保的金豆数', 70)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'SubsistenceAllowancesNumber', 5, N'每天领取低保的最多次数', N'低保每日次数', N'键值：每天领取低保的最多次数', 75)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'SubsistenceAllowancesConditionMB', 1000, N'手机救济金玩家金豆不能低于', N'手机救济金领取条件', N'键值：领取手机救济金玩家金豆不能低于该金豆数', 83)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'SubsistenceAllowancesGoldMB', 1000, N'每次手机救济金的金豆数', N'手机救济金每次金额', N'键值：每次手机救济金的金豆数', 84)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'SubsistenceAllowancesNumberMB', 5, N'每天领取手机救济金的最多次数', N'手机救济金每日次数', N'键值：每天领取手机救济金的最多次数', 85)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'SubsistenceAllowancesTimeMB', 3600, N'领取手机救济金时间间隔', N'领取手机救济金时间间隔', N'键值：领取手机救济金时间间隔', 86)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'TaskTakeCount', 5, N'每天可领取任务的最大数目', N'领取任务数目', N'键值：每天可领取任务的最大数目', 101)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'TransferMaxTax', 1000, N'转账封顶税收！', N'转账税收封顶', N'键值：银行转账封顶税收，0-不封顶', 65)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'TransferPrerequisite', 10000, N'转账条件，转账金豆数必须大于此数才可转账！', N'转账条件', N'键值：表示转账金豆数必须大于此数才可转账', 50)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'TransferStauts', 1, N'转账功能被关闭，请留意网站公告', N'转账状态', N'键值：转账是否开启，键值：0-关闭转账，1-开启转账', 45)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'WinExperience', 10, N'赢局奖励的经验值', N'赢局经验', N'键值：赢局奖励的经验值', 100)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'RateCard', 20000, N'点卡充值人民币与金豆的汇率', N'点卡充值比率', N'键值：点卡充值金豆的汇率', 3)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'WinRemind', 10000000, N'玩家在游戏中赢取金豆超过该值提醒', N'报警信息设置', N'键值：玩家在游戏中赢取超过该金豆提醒', 102)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'PayMusic', 1, N'玩家充值后台提示音', N'充值提示音', N'键值：0不开启  1开启', 104)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'EducateGrantScore', 10000000, N'进入房间将会得到这么多体验币', N'练习币设置', N'键值：表示赠送的练习币数量', 101)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'LoginErrorTimes', 6, N'密码错误次数锁定账号', N'锁定账号', N'键值：密码输入错误次数过多锁定账号', 120)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'RemindTimes', 3, N'超过该次数后会提示', N'锁定提示', N'键值：密码错误次数超出该数会提示', 122)
INSERT INTO [dbo].[SystemStatusInfo] ([StatusName], [StatusValue], [StatusString], [StatusTip], [StatusDescription], [SortID]) VALUES (N'LockTime', 24, N'锁定时间 单位:小时', N'锁定时间', N'键值：密码错误多次后锁定账号时间', 124)
